#ifndef WBXML_CONFIG_H
#define WBXML_CONFIG_H

#define WBXML_LIB_VERSION "1.2.3"
#define WBXML_ENCODER_USE_STRTBL 1
#define WBXML_SUPPORT_WML 1
#define WBXML_SUPPORT_WTA 1
#define WBXML_SUPPORT_SI 1
#define WBXML_SUPPORT_SL 1
#define WBXML_SUPPORT_CO 1
#define WBXML_SUPPORT_PROV 1
#define WBXML_SUPPORT_EMN 1
#define WBXML_SUPPORT_DRMREL 1
#define WBXML_SUPPORT_OTA_SETTINGS 1
#define WBXML_SUPPORT_SYNCML 1
#define WBXML_SUPPORT_WV 1
#define WBXML_SUPPORT_AIRSYNC 1
#define WBXML_SUPPORT_CONML 1

#endif /* WBXML_CONFIG_H */
